# Generated by Django 4.2.4 on 2023-10-13 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('payment_status', models.CharField(max_length=12)),
                ('payment_by', models.CharField(max_length=100)),
                ('borrowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.borrowing')),
            ],
        ),
    ]
